markdown: kramdown
logo_text: Samily
logo_subtext: tea, cat and a frond-end engineer
email: samilywang@icloud.com
github_username: samilywang
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
